FROM ghcr.io/smocker-dev/smocker:1.0.0

RUN apk --no-cache add bash curl

LABEL org.opencontainers.image.authors="andrejs" \
    org.opencontainers.image.title="smocker" \
    org.opencontainers.image.description="Smocker mock server image with curl and bash"
