#!/user/bin/env bash
#MISE description="Bump chart version"
#USAGE flag "--chart <chart_name>" help="Chart name" {
#USAGE choices "buildkit-service" "smocker"
#USAGE }
#USAGE flag "--version-segment <version_segment>" help="Version segment to bump" {
#USAGE choices "patch" "minor" "major"
#USAGE }

set -e

source "${MISE_PROJECT_ROOT}/.mise-tasks/utils.sh"

chart=${usage_chart}
version_segment=${usage_version_segment}

log "setup git"
git config user.name github-actions
git config user.email github-actions@github.com

log "bump chart version"
helm local-chart-version bump -c charts/$chart -s $version_segment

log "update docs"
helm-docs -c charts/$chart

log "create release commit"
version=$(helm local-chart-version get -c charts/$chart)
git commit -a -m "$chart: Update chart to version $version"

log "push changes"
git push
