#!/usr/bin/env bash
#MISE description="Run kubeconform to validate chart templates"

set -e

source "${MISE_PROJECT_ROOT}/.mise-tasks/utils.sh"

charts=($(changed-charts))

if [ ${#charts[@]} -eq 0 ]; then
  log "No chart changes detected!"
  exit
fi

for chart_dir in "${charts[@]}"; do
  for yaml in $chart_dir/ci/ci-*.yaml; do
    values_opt=$([ -f "$yaml" ] && echo "-f $yaml" || echo "")

    message="Validating $chart_dir with $yaml"
    length=$(echo "$message" | awk '{print length}')
    delimiter=$(head -c $length </dev/zero | tr '\0' '=')

    log "$delimiter"
    log "$message"
    log "$delimiter"

    helm dependency update $chart_dir
    helm template $chart_dir $values_opt | kubeconform -strict -verbose -kubernetes-version "${KUBERNETES_VERSION}"
  done
done
