name: Release

on:
  push:
    branches:
      - main
    paths:
      - charts/*/Chart.yaml

env:
  CT_TARGET_BRANCH: main
  MISE_AUTO_INSTALL: "false"

jobs:
  lint:
    if: contains(github.event.head_commit.message, 'Update chart to version')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install helm-docs
        uses: jdx/mise-action@v2
        with:
          install_args: "helm-docs"
      - name: Setup chart testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Lint charts
        run: ct lint --config .github/config/ct-lint.yaml
      - name: Lint docs
        run: mise lint-docs

  release:
    if: contains(github.event.head_commit.message, 'Update chart to version')
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install helm
        uses: jdx/mise-action@v2
        with:
          install_args: "helm"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"
