name: Build smocker

on:
  pull_request:
    branches:
      - main
    paths:
      - charts/smocker/Dockerfile
  push:
    branches:
      - main
    paths:
      - charts/smocker/Dockerfile

jobs:
  docker:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3.3.0
        with:
          username: andrcuns
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set smocker version
        id: version
        run: |
          VERSION=$(cat charts/smocker/Dockerfile | grep -E '^FROM thiht/smocker:' | cut -d ':' -f 2)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
      - name: Docker tags
        id: tags
        uses: docker/metadata-action@v5
        with:
          images: andrcuns/smocker
          flavor: latest=false
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.version.outputs.VERSION }}
      - name: Build and push
        uses: docker/build-push-action@v6.13.0
        with:
          context: charts/smocker
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.tags.outputs.tags }}
