name: Bump version

on:
  workflow_dispatch:
    inputs:
      semver:
        description: Version component to bump
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      chart:
        description: Chart name
        required: true
        type: choice
        options:
          - buildkit-service
          - smocker

env:
  MISE_AUTO_INSTALL: "false"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.RELEASE_SSH_KEY }}
      - name: Install helm-docs
        uses: jdx/mise-action@v2
        with:
          install_args: "helm-docs"
      - name: Update version
        run: mise bump-version --chart ${{ inputs.chart }} --version-segment ${{ inputs.semver }}
